### ISSUE TITLE
Example Code Generates Exception

### ISSUE THREAD

**Issue by cleopold73** [arieb/python-testdata#4]
CentOS 6.5 
Python 2.6.6
Installed with pip install python-testdata

Example DictFactory code errors with the following:

/usr/bin/python /home/corey/PycharmProjects/test.py
Traceback (most recent call last):
  File "/home/corey/PycharmProjects/test.py", line 14, in <module>
    for user in Users().generate(10): # let say we only want 10 users
  File "/usr/lib/python2.6/site-packages/testdata/dictionary.py", line 27, in **init**
    self._child_factories = deepcopy(self._child_factory_tree)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 338, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 334, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 338, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 323, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.6/copy_reg.py", line 93, in __newobj__
    return cls.**new**(cls, *args)
TypeError: instancemethod expected at least 2 arguments, got 0

Process finished with exit code 1

**Comment by arieb** [comment]
I think this issue may be related to a bug in the deepcopy module in python 2.6. that was fixed in python 2.7. the example code works on 2.7
